name: Reusable – Development Build (BuildKit)

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: ".NET SDK version (for NuGet pack job)"
        required: false
        type: string
        default: '9.0.x'
      tag_prefix:
        description: "Prefix for dev image tags"
        required: false
        type: string
        default: 'dev'
    secrets:
      NUGET_PACKAGES_AUTH_TOKEN:
        required: true

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-reusable
  cancel-in-progress: true

jobs:
  init_workflow:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      containers: ${{ steps.container_matrix.outputs.matrix }}
      nuget_packages: ${{ steps.nuget_matrix.outputs.matrix }}
      repo_owner_lower: ${{ steps.split.outputs._0 }}
      repo_name: ${{ steps.split.outputs._1 }}
      safe_branch: ${{ steps.branch.outputs.SAFE_BRANCH }}
      short_sha: ${{ steps.sha.outputs.SHORT_SHA }}
      ghpk_key: ${{ steps.detect-ghpk.outputs.GHPK_KEY }}
    steps:
      - uses: actions/checkout@v4

      - id: container_matrix
        name: Load container matrix
        run: 'echo "matrix={""container"": $(jq -c . ./src/strategy_matrix_containers.json)}" >> "$GITHUB_OUTPUT"'

      - id: nuget_matrix
        name: Load NuGet package matrix (optional)
        run: 'echo "matrix={""nuget_package"": $(jq -c . ./src/strategy_matrix_nuget_packages.json 2>/dev/null || echo "[]")}" >> "$GITHUB_OUTPUT"'

      - id: owner_repo
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - uses: winterjung/split@v2
        id: split
        with:
          msg: ${{ steps.owner_repo.outputs.lowercase }}
          separator: "/"

      - id: branch
        name: Normalize branch for tags
        shell: bash
        run: |
          set -euo pipefail
          b="${GITHUB_REF_NAME}"
          safe=$(echo "$b" | tr '[:upper:]' '[:lower:]' | tr '/_' '-' | tr -cd 'a-z0-9-')
          echo "SAFE_BRANCH=$safe" >> "$GITHUB_OUTPUT"

      - id: sha
        name: Short SHA
        shell: bash
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - id: detect-ghpk
        name: Detect GitHub Packages NuGet source key
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update && sudo apt-get install -y xmlstarlet
          KEY=$(xmlstarlet sel -t -m '//packageSources/add[contains(@value,"nuget.pkg.github.com")]' -v @key -n nuget.config | head -n1)
          if [[ -z "$KEY" ]]; then
            echo "::warning::No GitHub Packages source found in nuget.config (NuGet job may be skipped)"
          else
            echo "GHPK_KEY=$KEY" >> "$GITHUB_OUTPUT"
          fi

      - name: Set repo owner in nuget.config (if present)
        shell: bash
        run: |
          if [[ -f nuget.config ]]; then
            OWNER="${{ github.repository_owner }}"
            sed -i "s|__REPO_OWNER__|$OWNER|g" nuget.config || true
          fi

  docker:
    if: ${{ !contains(toJson(needs.init_workflow.outputs.containers), '[]') }}
    runs-on: ubuntu-24.04
    needs: [init_workflow]
    timeout-minutes: 45
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix: ${{ fromJson(needs.init_workflow.outputs.containers) }}
    env:
      REGISTRY: ${{ vars.DOCKER_IMAGE_PKGS }}   # e.g., ghcr.io
      OWNER: ${{ needs.init_workflow.outputs.repo_owner_lower }}
      IMAGE_NAME: ${{ matrix.container }}
      TAG1: ${{ inputs.tag_prefix }}-${{ needs.init_workflow.outputs.safe_branch }}-${{ needs.init_workflow.outputs.short_sha }}
      TAG2: ${{ inputs.tag_prefix }}-${{ needs.init_workflow.outputs.safe_branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: project_name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_NAME }}
          
      - name: Set up Docker Buildx (BuildKit)
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (full Dockerfile, BuildKit secrets)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/${{ env.IMAGE_NAME }}/Dockerfile
          push: true
          provenance: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ steps.project_name.outputs.lowercase }}:${{ env.TAG1 }}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ steps.project_name.outputs.lowercase }}:${{ env.TAG2 }}
          build-args: |
            REPO_OWNER=${{ env.OWNER }}
          secrets: |
            NUGET_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

  nuget:
    if: ${{ !contains(toJson(needs.init_workflow.outputs.nuget_packages), '[]') && needs.init_workflow.outputs.ghpk_key != '' }}
    name: "nuget ${{ matrix.nuget_package }}:(dev)"
    needs: [init_workflow]
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.init_workflow.outputs.nuget_packages) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Resolve NuGet config path
        run: echo "CONFIG=$GITHUB_WORKSPACE/nuget.config" >> "$GITHUB_ENV"

      - name: Set repo owner in nuget.config
        run: |
          sed -i "s|__REPO_OWNER__|${{ github.repository_owner }}|g" "$CONFIG"

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
            **/*.csproj

      - name: Configure credentials for GitHub Packages source
        env:
          # Prefer PAT with read:packages if reading other repos/orgs:
          NUGET_TOKEN: ${{ secrets.NUGET_PACKAGES_AUTH_TOKEN }}
          # NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          dotnet nuget update source "${{ needs.init_workflow.outputs.ghpk_key }}" \
            --username "$GITHUB_ACTOR" \
            --password "$NUGET_TOKEN" \
            --store-password-in-clear-text \
            --configfile "$CONFIG"

      - name: Restore
        working-directory: src/${{ matrix.nuget_package }}
        run: dotnet restore ${{ matrix.nuget_package }}.csproj --configfile "$CONFIG"

      - name: Build
        working-directory: src/${{ matrix.nuget_package }}
        run: dotnet build ${{ matrix.nuget_package }}.csproj --configuration Release

      - name: Prepare artifacts
        run: mkdir -p "$GITHUB_WORKSPACE/artifacts/${{ matrix.nuget_package }}"

      - name: Pack (dev pre-release)
        working-directory: src/${{ matrix.nuget_package }}
        run: |
          ver="0.0.0-${{ inputs.tag_prefix }}.${{ needs.init_workflow.outputs.safe_branch }}.${{ needs.init_workflow.outputs.short_sha }}"
          dotnet pack ${{ matrix.nuget_package }}.csproj --configuration Release --no-build --output "$GITHUB_WORKSPACE/artifacts/${{ matrix.nuget_package }}" -p:PackageVersion="$ver"

      - name: Push package (optional)
        run: |
          ver="0.0.0-${{ inputs.tag_prefix }}.${{ needs.init_workflow.outputs.safe_branch }}.${{ needs.init_workflow.outputs.short_sha }}"
          dotnet nuget push "$GITHUB_WORKSPACE/artifacts/${{ matrix.nuget_package }}/${{ matrix.nuget_package }}.$ver.nupkg" --api-key ${{ secrets.NUGET_PACKAGES_AUTH_TOKEN }} --source "${{ vars.NUGET_PKG_INDEX }}"
