name: Reusable – Main Release (BuildKit)

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: ".NET SDK version"
        required: false
        type: string
        default: '9.0.x'
    secrets:
      NUGET_PACKAGES_AUTH_TOKEN:
        required: true

permissions:
  contents: write   # tag/release
  packages: write   # GHCR + GitHub Packages (NuGet)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-reusable
  cancel-in-progress: true

jobs:
  init_workflow:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      containers: ${{ steps.container_matrix.outputs.matrix }}
      nuget_packages: ${{ steps.nuget_matrix.outputs.matrix }}
      repo_owner_lower: ${{ steps.split.outputs._0 }}
      repo_name: ${{ steps.split.outputs._1 }}
      version: ${{ steps.semver.outputs.next }}
      version_no_v: ${{ steps.version.outputs.substring }}
      ghpk_key: ${{ steps.detect-ghpk.outputs.GHPK_KEY }}
    steps:
      - uses: actions/checkout@v4

      - id: container_matrix
        name: Load container matrix
        run: 'echo "matrix={""container"": $(jq -c . ./src/strategy_matrix_containers.json)}" >> "$GITHUB_OUTPUT"'

      - id: nuget_matrix
        name: Load NuGet package matrix
        run: 'echo "matrix={""nuget_package"": $(jq -c . ./src/strategy_matrix_nuget_packages.json)}" >> "$GITHUB_OUTPUT"'

      - id: owner_repo
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - uses: winterjung/split@v2
        id: split
        with:
          msg: ${{ steps.owner_repo.outputs.lowercase }}
          separator: "/"

      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          minorList: feat
          patchList: fix, docs, style, refactor, perf, test, build, ci, chore

      - uses: bhowell2/github-substring-action@v1.0.0
        id: version
        name: Extract numeric version (drop 'v')
        with:
          value: ${{ steps.semver.outputs.next }}
          index_of_str: "v"

      - id: detect-ghpk
        name: Detect GitHub Packages NuGet source key
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update && sudo apt-get install -y xmlstarlet
          KEY=$(xmlstarlet sel -t -m '//packageSources/add[contains(@value,"nuget.pkg.github.com")]' -v @key -n nuget.config | head -n1)
          if [[ -z "$KEY" ]]; then
            echo "::error::No GitHub Packages source found in nuget.config"
            exit 1
          fi
          echo "GHPK_KEY=$KEY" >> "$GITHUB_OUTPUT"

      - name: Set repo owner in nuget.config
        run: |
          OWNER="${{ github.repository_owner }}"
          sed -i "s|__REPO_OWNER__|$OWNER|g" nuget.config

  release:
    name: "release (${{ needs.init_workflow.outputs.version }})"
    runs-on: ubuntu-24.04
    needs: [init_workflow]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Create version tag
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git tag ${{ needs.init_workflow.outputs.version }}
          git push origin ${{ needs.init_workflow.outputs.version }}

      - uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.init_workflow.outputs.version }}
          includeInvalidCommits: true

      - uses: ncipollo/release-action@v1
        with:
          name: "Release ${{ needs.init_workflow.outputs.version }}"
          tag: ${{ needs.init_workflow.outputs.version }}
          bodyFile: "CHANGELOG.md"

  docker:
    if: ${{ !contains(toJson(needs.init_workflow.outputs.containers), '[]') }}
    runs-on: ubuntu-24.04
    needs: [init_workflow, release]
    timeout-minutes: 45
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix: ${{ fromJson(needs.init_workflow.outputs.containers) }}
    env:
      REGISTRY: ${{ vars.DOCKER_IMAGE_PKGS }}   # e.g., ghcr.io
      OWNER: ${{ needs.init_workflow.outputs.repo_owner_lower }}
      IMAGE_NAME: ${{ matrix.container }}
      VERSION: ${{ needs.init_workflow.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - id: project_name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx (BuildKit)
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (full Dockerfile, BuildKit secrets)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/${{ env.IMAGE_NAME }}/Dockerfile
          push: true
          provenance: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ steps.project_name.outputs.lowercase }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ steps.project_name.outputs.lowercase }}
          build-args: |
            REPO_OWNER=${{ env.OWNER }}
          secrets: |
            NUGET_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

  nuget:
    if: ${{ !contains(toJson(needs.init_workflow.outputs.nuget_packages), '[]') }}
    name: "nuget ${{ matrix.nuget_package }}:(${{ needs.init_workflow.outputs.version }})"
    needs: [init_workflow, release]
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.init_workflow.outputs.nuget_packages) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
            **/*.csproj

      - name: Configure credentials for GitHub Packages source
        env:
          NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          dotnet nuget update source "${{ needs.init_workflow.outputs.ghpk_key }}" \
            --username "$GITHUB_ACTOR" \
            --password "$NUGET_TOKEN" \
            --store-password-in-clear-text \
            --configfile "nuget.config"

      - name: Restore
        working-directory: src/${{ matrix.nuget_package }}
        run: dotnet restore ${{ matrix.nuget_package }}.csproj

      - name: Build
        working-directory: src/${{ matrix.nuget_package }}
        run: dotnet build ${{ matrix.nuget_package }}.csproj --configuration Release

      - name: Prepare artifacts
        run: mkdir -p "$GITHUB_WORKSPACE/artifacts/${{ matrix.nuget_package }}"

      - name: Pack
        working-directory: src/${{ matrix.nuget_package }}
        run: dotnet pack ${{ matrix.nuget_package }}.csproj --configuration Release --no-build --output "$GITHUB_WORKSPACE/artifacts/${{ matrix.nuget_package }}" -p:PackageVersion=${{ needs.init_workflow.outputs.version_no_v }}

      - name: Push package
        run: dotnet nuget push "$GITHUB_WORKSPACE/artifacts/${{ matrix.nuget_package }}/${{ matrix.nuget_package }}.${{ needs.init_workflow.outputs.version_no_v }}.nupkg" --api-key ${{ secrets.NUGET_PACKAGES_AUTH_TOKEN }} --source "${{ vars.NUGET_PKG_INDEX }}"
